### PR TITLE
migrate keychain prefix

### PR DESCRIPTION
**Pull request by cnotethegr8**

### CODE REVIEW

**Comment by cnotethegr8** [comment]
@natanrolnik how do you feel about this PR? I want to move away from the previous keychain prefix, which is somewhat random.

**Comment by natanrolnik** [comment]
@cnotethegr8 I'm not sure about this change. I personally don't see any need - yes, the prefix has to do with Stellar and not Kin. Considering we have apps in production using it, this could potentially lead to some problems...
@avi-kik any thoughts?

**Comment by avi-kik** [comment]
The only problem with changing the prefix is that apps which don't call migrate will be broken when they update the SDK.  Breaking changes should be considered more carefully.

**Comment by cnotethegr8** [comment]
@avi-kik thats why I made the migrate an internal function and am calling it within the sdk. With this update the user would not need to know about this change.

**Comment by cnotethegr8** [comment]
This PR is being closed because all changes moving forward will take place in the KinSDK repo.

**Pull request closed without merging**
